routes/web.php
<?php

Route::resource('employees', 'EmployeeController');
Route::resource('points', 'PointController');
Route::resource('workloads', 'WorkloadController');
Route::get('reports', 'ReportController@index')->name('reports.index');
Route::post('reports', 'ReportController@generateByEmployee');

Route::post('employees/{id}/workloads', 'EmployeeController@createWorkload')->name('employee.workloads');
Route::get('employees/{id}/workloads', 'EmployeeController@workload')->name('employee.workloads');



Route::get('employees/{id}/status', 'EmployeeController@alterStatus');

app/Models/Workload.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Workload extends Model
{
	protected $fillable = ['day', 'start_time', 'exit_time'];


	public function employees()
	{
		return $this->belongsToMany('employee_workload');
	}
}

app/Http/Controllers/WorkloadController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Workload;


class WorkloadController extends Controller
{

	private $workload;

    function __construct(Workload $workload)
    {
    	$this->workload = $workload;
    }

    public function index()
    {
        $days = array(
        ['key'=>'segunda', 'value' => 'Segunda'],
        ['key'=>'terca', 'value' => 'Terca'],
        ['key'=>'quarta', 'value' => 'Quarta'],
        ['key'=>'quinta', 'value' => 'Quinta'],
        ['key'=>'sexta', 'value' => 'Sexta'],
        ['key'=>'sabado', 'value' => 'Sabado'],
        ['key'=>'domingo', 'value' => 'Domingo']);

    	$workloads = $this->workload->orderBy('start_time', 'asc')->get();
        return view('workload.index', compact('workloads', 'days')) ;
    }

    public function create()
    {
    	$title = "Cadatrar espediente";
    	return view('workload.create', compact('title'));
    }


    public function store(Request $request)
    {
           $request->validate([
            'day' => 'required',
            'start_time' => 'required',
            'exit_time' => 'required'
    ]);
                    $this->workload->create($request->all());
    	return redirect()->route('workloads.index');
    }

    public function destroy($id)
    {
         $workload = $this->workload->find($id);
         $workload->delete();
         return redirect()->route('workloads.index');
    }

}

resources/views/workload/copia index.blade.php
@extends('templates.layout')

@section('content')


	<div class="container mt-4">
	<div class="row justify-content-end">
		<div class="form-group col col-lg-1">
			<a href="{{ route('workloads.create') }}" class="btn btn-primary">novo</a>
		</div>
	</div>


<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      <a class="list-group-item list-group-item-action active" id="list-segunda-list" data-toggle="list" href="#segunda" role="tab" aria-controls="home">Segunda</a>
      <a class="list-group-item list-group-item-action" id="list-terca-list" data-toggle="list" href="#terca" role="tab" aria-controls="profile">Terça</a>
      <a class="list-group-item list-group-item-action" id="list-quarta-list" data-toggle="list" href="#quarta" role="tab" aria-controls="messages">Quarta</a>
      <a class="list-group-item list-group-item-action" id="list-quinta-list" data-toggle="list" href="#quinta" role="tab" aria-controls="settings">Quinta</a>
      <a class="list-group-item list-group-item-action" id="list-sexta-list" data-toggle="list" href="#sexta" role="tab" aria-controls="settings">Sexta</a>
      <a class="list-group-item list-group-item-action" id="list-sabado-list" data-toggle="list" href="#sabado" role="tab" aria-controls="settings">Sabado</a>
      <a class="list-group-item list-group-item-action" id="list-domingo-list" data-toggle="list" href="#domingo" role="tab" aria-controls="settings">Domingo</a>
    </div>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="segunda" role="tabpanel" aria-labelledby="list-segunda-list">
      	@if(isset($workloads))
      	<table class="table table-bordered">
      		<thead>
      			<tr>
      				<th>Entrada/Saída</th>
      				<th>Ação</th>
      			</tr>
      		</thead>
      		<tbody>
      			@foreach($workloads as $workload)
      				@if($workload->day==='Segunda')
						<tr>
							<td>
								{{$workload->start_time. '-'. $workload->exit_time}}
							</td>
							<td><a href="">deletar</a></td>
						</tr>
					@endif
      			 @endforeach
      		</tbody>
      	</table>
      	@endif
      </div>
      <div class="tab-pane fade" id="terca" role="tabpanel" aria-labelledby="list-terca-list">
      	       	@if(isset($workloads))
      	<table class="table table-bordered">
      		<thead>
      			<tr>
      				<th>Entrada/Saída</th>
      				<th>Ação</th>
      			</tr>
      		</thead>
      		<tbody>
      			@foreach($workloads as $workload)
      				@if($workload->day==='Terça')
						<tr>
							<td>
								{{$workload->start_time. '-'. $workload->exit_time}}
							</td>
							<td><a href="">deletar</a></td>
						</tr>
					@endif
      			 @endforeach
      		</tbody>
      	</table>
      	@endif
      </div>
      <div class="tab-pane fade" id="quarta" role="tabpanel" aria-labelledby="list-quarta-list">
                        @if(isset($workloads))
            <table class="table table-bordered">
                  <thead>
                        <tr>
                              <th>Entrada/Saída</th>
                              <th>Ação</th>
                        </tr>
                  </thead>
                  <tbody>
                        @foreach($workloads as $workload)
                              @if($workload->day==='Quarta')
                                    <tr>
                                          <td>
                                                {{$workload->start_time. '-'. $workload->exit_time}}
                                          </td>
                                          <td><a href="">deletar</a></td>
                                    </tr>
                              @endif
                         @endforeach
                  </tbody>
            </table>
            @endif
      </div>
      <div class="tab-pane fade" id="quinta" role="tabpanel" aria-labelledby="list-settings-list">
      	      	@if(isset($workloads))
      	<table class="table table-bordered">
      		<thead>
      			<tr>
      				<th>Entrada/Saída</th>
      				<th>Ação</th>
      			</tr>
      		</thead>
      		<tbody>
      			@foreach($workloads as $workload)
      				@if($workload->day==='Quinta')
						<tr>
							<td>
								{{$workload->start_time. '-'. $workload->exit_time}}
							</td>
							<td><a href="">deletar</a></td>
						</tr>
					@endif
      			 @endforeach
      		</tbody>
      	</table>
      	@endif
      </div>
      <div class="tab-pane fade" id="sexta" role="tabpanel" aria-labelledby="list-messages-list">
      	      	@if(isset($workloads))
      	<table class="table table-bordered">
      		<thead>
      			<tr>
      				<th>Entrada/Saída</th>
      				<th>Ação</th>
      			</tr>
      		</thead>
      		<tbody>
      			@foreach($workloads as $workload)
      				@if($workload->day==='Sexta')
						<tr>
							<td>
								{{$workload->start_time. '-'. $workload->exit_time}}
							</td>
							<td><a href="">deletar</a></td>
						</tr>
					@endif
      			 @endforeach
      		</tbody>
      	</table>
      	@endif
      </div>
      <div class="tab-pane fade" id="sabado" role="tabpanel" aria-labelledby="list-settings-list">
      	      	@if(isset($workloads))
      	<table class="table table-bordered">
      		<thead>
      			<tr> 
      				<th>Entrada/Saída</th>
      				<th>Ação</th>
      			</tr>
      		</thead>
      		<tbody>
      			@foreach($workloads as $workload)
      				@if($workload->day==='Sabado')
						<tr>
							<td>
								{{$workload->start_time. '-'. $workload->exit_time}}
							</td>
							<td><a href="">deletar</a></td>
						</tr>
					@endif
      			 @endforeach
      		</tbody>
      	</table>
      	@endif
      </div>

  <div class="tab-pane fade" id="domingo" role="tabpanel" aria-labelledby="list-domingo-list">
      	      	@if(isset($workloads))
      	<table class="table table-bordered">
      		<thead>
      			<tr>
      				<th>Entrada/Saída</th>
      				<th>Ação</th>
      			</tr>
      		</thead>
      		<tbody>
      			@foreach($workloads as $workload)
      				@if($workload->day==='Domingo')
						<tr>
							<td>
								{{$workload->start_time. '-'. $workload->exit_time}}
							</td>
							<td><a href="">deletar</a></td>
						</tr>
					@endif
      			 @endforeach
      		</tbody>
      	</table>
      	@endif
      </div>

    </div>
  </div>
</div>



	</div>

@endsection

resources/views/workload/create.blade.php
@extends('templates.layout')

@section('content')

	{{ Form::open(['route' => 'workloads.store', 'method'=>'post']) }}
	

<div class="container mt-4">
	<div class="row">
		<div class="form-group col col-lg-3">
			<label for="cpf">Data Entrada</label>
			<select class="form-control" name="day">
				<option value="Segunda">Segunda</option>
				<option value="Terça">Terça</option>
				<option value="Quarta">Quarta</option>
				<option value="Quinta">Quinta</option>
				<option value="Sexta">Sexta</option>
				<option value="Sabado">Sabado</option>
				<option value="Domingo">Domingo</option>
			</select>
			@if($errors->has('cpf')) 
			<p class="help-block">{{ $errors->first('cpf') }}</p>
			@endif
		</div>

		<div class="form-group col col-lg-3">
			<label for="start_time">Hora Entrada</label>
			<input id="start_time" type="time" name="start_time" class="form-control">
			@if($errors->has('cpf')) 
			<p class="help-block">{{ $errors->first('cpf') }}</p>
			@endif
		</div>

	<div class="form-group col col-lg-3">
		<label for="exit_time">Hora Saída</label>
		<input id="exit_time" type="time" name="exit_time" class="form-control">
		@if($errors->has('cpf')) 
		<p class="help-block">{{ $errors->first('cpf') }}</p>
		@endif
	</div>

</div>

<div class="row">
		<div class="form-group col col-lg-3">
		<input type="submit" class="form-control btn btn-primary">
	</div>
</div>

</div>

	{{ Form::close() }}
@endsection

resources/views/workload/index.blade.php
@extends('templates.layout')

@section('content')


	<div class="container mt-4">
	<div class="row justify-content-end">
		<div class="form-group col col-lg-1">
			<a href="{{ route('workloads.create') }}" class="btn btn-primary">novo</a>
		</div>
	</div>


<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      @foreach($days as $day)
      <a class="list-group-item list-group-item-action {{ $day['key'] == 'segunda' ? 'active' : '' }}" id="list-{{$day['key']}}-list" data-toggle="list" href="#{{$day['key']}}" role="tab" aria-controls="home">{{$day['value']}}</a>
       @endforeach
    </div>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
            @if(isset($workloads))
            @foreach($days as $day)
      <div class="tab-pane fade show {{ $day['key'] == 'segunda' ? 'active' : '' }}" id="{{$day['key']}}" role="tabpanel" aria-labelledby="list-{{$day['key']}}-list">
      	@if(isset($workloads))
      	<table class="table table-bordered">
      		<thead>
      			<tr>
      				<th>Entrada/Saída</th>
      				<th>Ação</th>
      			</tr>
      		</thead>
      		<tbody>
      			@foreach($workloads as $workload)
      				@if($workload->day==$day['value'])
						<tr>
							<td>
								{{$workload->start_time. '-'. $workload->exit_time}}
							</td>
							<td>

{!! Form::open(['method' => 'Delete', 'route' => ['workloads.destroy', $workload->id]]) !!}
<button type="submit" class="btn btn-danger" style="cursor: pointer;">
  <i class="fa fa-times" aria-hidden="true"></i>
</button>
{!! Form::close() !!}
</td>
						</tr>
					@endif
      			 @endforeach
      		</tbody>
      	</table>
           @endif  
 
       </div>
             @endforeach
    @endif 
     </div>
   </div>
 </div>
</div>

@endsection