routes/web.php
<?php

Route::resource('employees', 'EmployeeController');
Route::resource('points', 'PointController');
Route::resource('workloads', 'WorkloadController');
Route::get('reports', 'ReportController@index')->name('reports.index');
Route::post('reports', 'ReportController@generateByEmployee');

Route::post('employees/{id}/workloads', 'EmployeeController@createWorkload')->name('employee.workloads');
Route::get('employees/{id}/workloads', 'EmployeeController@workload')->name('employee.workloads');



Route::get('employees/{id}/status', 'EmployeeController@alterStatus');

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
	protected $fillable = ['cpf', 'name', 'function', 'admission','status'];

	public function points() {
		return $this->hasMany(\App\Models\Point::class,'employee_id', 'id');
	}

		public function workloads()
	{
		return $this->belongsToMany(\App\Models\Workload::class,'employee_workload');
	}

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeFormRequest;
use Illuminate\Http\Request;
use App\Models\Employee;
class EmployeeController extends Controller
{
	private $employee;

	function __construct(Employee $employee)
	{
		$this->employee = $employee;
	}

     public function index()
    {
      $title = "Colaboradores";
      $employees = $this->employee->orderBy('id')->paginate(4);
    	return view('employee.index', compact('employees','title'));
    }

    public function edit($id) 
    {
      $title = "Editar Colaborador";
      $employee = $this->employee->find($id);
     return view('employee.edit',compact('employee','title'));
    }

    public function update(EmployeeFormRequest $request, $id)
    {
      $employee = $this->employee->find($id);
      $employee->update($request->all());
      return redirect()->route('employees.index');
    }

    public function store(EmployeeFormRequest $request)
    {        
            $request['status'] = $request->all()['status'] ?? 'off';
            $data = $request->all();
            $this->employee->create($data);
    	return redirect()->route('employees.index');
    }

    public function create()
    {
       $title = "Novo colaborador";
     	return view('employee.create', compact('title'));
    }

    public function show($id) {

    }

    public function alterStatus($id)
    {
       $employee = $this->employee->find($id);
       $status = $employee->status == 'on' ? 'off' : 'on';
       $employee->status = $status;
       $employee->save();
       return redirect()->route('employees.index');
    }

     public function destroy($id) {


     }

     public function createWorkload($id, Request $request)
     {
       $employee = $this->employee->find($id);
        if(isset($request->day)) {
        $workload =  \App\Models\Workload::whereIn('id', $request->day)->get();
        $employee->workloads()->sync($workload);
        }
     
      return $this->workload($employee->id);
     }

    public function workload($id) {
      $title = "Expediente colaborador";
      $days = array(
        ['key'=>'segunda', 'value' => 'Segunda'],
        ['key'=>'terca', 'value' => 'Terca'],
        ['key'=>'quarta', 'value' => 'Quarta'],
        ['key'=>'quinta', 'value' => 'Quinta'],
        ['key'=>'sexta', 'value' => 'Sexta'],
        ['key'=>'sabado', 'value' => 'Sabado'],
        ['key'=>'domingo', 'value' => 'Domingo']);

      $workloads = \App\Models\Workload::orderBy('start_time', 'asc')->get();
      $employee = $this->employee->find($id);
      $employee->workloads;
      return view('employee.workload', compact('workloads','employee','title', 'days'));
    }


}

resources/views/employee/create.blade.php
@extends('templates.layout')

@section('content')

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js">
	
</script>
<script type="text/javascript">
	
$(document).on('click', '.browse', function(){
  var file = $(this).parent().parent().parent().find('.file');
  file.trigger('click');
});
$(document).on('change', '.file', function(){
  $(this).parent().find('.form-control').val($(this).val().replace(/C:\\fakepath\\/i, ''));
});
	
</script>

<style type="text/css">
	.file {
  visibility: hidden;
  position: absolute;
}
</style>

{{ Form::open(['url' => 'employees', 'method' => 'POST', 'enctype' => 'multipart/form-data']) }}
 
 <h1>Cadastro de Funcionarios</h1>
 <p>preencha todos os campos</p>
<div class="container">
	
  <div class="input-group mb-3">
   	 <span class="input-group-addon">
        <input type="checkbox" name="status">
      </span>
      <span class="input-group-addon " >Ativo</span>
  </div>

  <div class="row">
  	<div class="form-group col-xs-12 col-md-6 col-lg-6">
      <input type="file" name="img[]" class="file">
      <div class="input-group col-xs-12">
        <span class="input-group-addon"><i class="glyphicon glyphicon-picture"></i></span>
        <input type="text" class="form-control input-lg" disabled placeholder="Imagem funcionário">
        <span class="input-group-btn">
          <button class="browse btn btn-primary input-lg" type="button"><i class="glyphicon glyphicon-search"></i> Buscar</button>
        </span>
      </div>
    </div>
  
  <div class="form-group col-xs-12 col-md-6 col-lg-6">
   	<input id="cpf" type="text" name="cpf" placeholder="CPF" class="form-control {{ $errors->has('cpf')? 'is-invalid':'' }}" value="{{ old('cpf') }}">
  	@if($errors->has('cpf')) 
  	<p class="invalid-feedback">{{ $errors->first('cpf') }}</p>
  	@endif
  </div>
</div>

<div class="row">
	<div class="form-group col-xs-12 col-md-6 col-lg-6">
	<label for="name">Nome</label>
	<input id="name" type="text" name="name" class="form-control {{ $errors->has('name')? 'is-invalid':'' }}" value="{{ old('name') }}">
		@if($errors->has('name')) 
	<p class="invalid-feedback">{{ $errors->first('name') }}</p>
	@endif
</div>

<div class="form-group col-xs-12 col-md-6 col-lg-6">
	<label for="function">Função</label>
	<input id="function" type="text" name="function" class="form-control {{ $errors->has('function')? 'is-invalid':'' }}" value="{{ old('function') }}">
	@if($errors->has('function')) 
  <p class="invalid-feedback">{{ $errors->first('function') }}</p>
	@endif
</div>
</div>
<div class="row">
	<div class="form-group  col-xs-12 col-md-6 col-lg-6">
	<label for="admission">Data de admissão</label>
	<input id="admission" type="text" name="admission" class="form-control {{ $errors->has('admission')? 'is-invalid':'' }}" value="{{ old('admission') }}">
		@if($errors->has('admission')) 
	<p class="invalid-feedback">{{ $errors->first('admission') }}</p>
	@endif
</div>
</div>


	<input type="submit" value="Enviar" class="btn btn-primary">

</div>

 {{ Form::close() }}


@endsection

resources/views/employee/edit.blade.php
@extends('templates.layout')

@section('content')

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js">
	
</script>

<script type="text/javascript">
	
$(document).on('click', '.browse', function(){
  var file = $(this).parent().parent().parent().find('.file');
  file.trigger('click');
});
$(document).on('change', '.file', function(){
  $(this).parent().find('.form-control').val($(this).val().replace(/C:\\fakepath\\/i, ''));
});
	
</script>

<style type="text/css">
	.file {
  visibility: hidden;
  position: absolute;
}
</style>

{{ Form::model($employee, ['route' => ['employees.update', $employee->id], 'method' => 'put']) }}
 
 <h1>Cadastro de Funcionarios</h1>
 <p>preencha todos os campos</p>
<div class="container">
	
  <div class="input-group mb-3">
   	 <span class="input-group-addon">
        <input type="checkbox" name="status" {{ $employee->status=='on' ? 'checked="true"' : ''  }}>
      </span>
      <span class="input-group-addon" >Ativo</span>
  	@if($errors->has('status')) 
  	<p class="help-block">{{ $errors->first('status') }}</p>
  	@endif
  </div>

  <div class="row">
  	<div class="form-group col-xs-12 col-md-6 col-lg-6">
      <input type="file" name="img[]" class="file">
      <div class="input-group col-xs-12">
        <span class="input-group-addon"><i class="glyphicon glyphicon-picture"></i></span>
        <input type="text" class="form-control input-lg" disabled placeholder="Imagem funcionário">
        <span class="input-group-btn">
          <button class="browse btn btn-primary input-lg" type="button"><i class="glyphicon glyphicon-search"></i> Buscar</button>
        </span>
      </div>
    </div>
  
  <div class="form-group col-xs-12 col-md-6 col-lg-6">
   	<input id="cpf" type="text" name="cpf" placeholder="CPF" class="form-control" value="{{ $employee->cpf or old('cpf') }}">
  	@if($errors->has('cpf')) 
  	<p class="help-block">{{ $errors->first('cpf') }}</p>
  	@endif
  </div>
</div>

<div class="row">
	<div class="form-group col-xs-12 col-md-6 col-lg-6">
	<label for="name">Nome</label>
	<input id="name" type="text" name="name" class="form-control" value="{{ $employee->name or old('name') }}">
		@if($errors->has('name')) 
	<p class="help-block">{{ $errors->first('name') }}</p>
	@endif
</div>

<div class="form-group col-xs-12 col-md-6 col-lg-6">
	<label for="function">Função</label>
	<input id="function" type="text" name="function" class="form-control" value="{{ $employee->function or old('function') }}">
	@if($errors->has('function')) 
	<p class="help-block">{{ $errors->first('function') }}</p>
	@endif
</div>
</div>

<div class="row">
	<div class="form-group  col-xs-12 col-md-6 col-lg-6">
	<label for="admission">Data de admissão</label>
	<input id="admission" type="text" name="admission" class="form-control" value="{{ $employee->admission or old('admission') }}">
		@if($errors->has('admission')) 
	<p class="help-block">{{ $errors->first('admission') }}</p>
	@endif
</div>
</div>


	<input type="submit" value="Enviar" class="btn btn-primary">

</div>

 {{ Form::close() }}


@endsection

resources/views/employee/index.blade.php
@extends('templates.layout')

@section('content')

<div class="container mt-4">

 <div class="row justify-content-end">
		<div class="form-group col col-lg-1">
			<a href="{{ route('employees.create') }}" class="btn btn-primary">novo</a>
		</div>
	</div>

	@if(isset($employees))
<table class="table">
	<thead>
		<tr class="thead-default">
			<th>cpf</th>
			<th>Nome</th>
			<th>Ações</th>
		</tr>
	</thead>
	<tbody>
		@foreach($employees as $employee)
		<tr>
			<td>{{ $employee->cpf }}</td>
			<td>{{ $employee->name }}</td>
			<td align="center">
			<a href="{{ url('employees/'. $employee->id. '/workloads/' ) }}" class="text-success"><i class="fa fa-calendar fa-2x" aria-hidden="true"></i></a>
			<a href="{{ route('employees.edit', ['id'=>$employee->id]) }}"><i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i></a>

			<a href="{{ url('employees/' . $employee->id) . '/status'  }}" class="{{ $employee->status=='on' ? 'text-success': 'text-danger'   }}"><i class="fa {{ $employee->status=='on' ? 'fa-unlock-alt': 'fa-lock' }} fa-2x" aria-hidden="true"></i></a></td>
		</tr>
		@endforeach
	</tbody>
</table>
@endif

 	<div class="row justify-content-center">{!! $employees->render("pagination::bootstrap-4") !!}</div>

</div>
@endsection

resources/views/employee/workload.blade.php
@extends('templates.layout')

@section('content')

@if(isset($workloads) && isset($employee))
	<div class="container mt-4">

	<div class="row justify-content-start">
		<div class="form-group col col-lg-12">
			<h2>Colaborador: {{ $employee->name }}</h2><hr>
		</div>
	</div>

{{ Form::open([ 'route' => ['employee.workloads', $employee->id] ,'method' => 'POST']) }}
<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      @foreach($days as $day)
      <a class="list-group-item list-group-item-action {{ $day['key'] == 'segunda' ? 'active' : '' }}" id="list-{{$day['key']}}-list" data-toggle="list" href="#{{$day['key']}}" role="tab" aria-controls="home">{{$day['value']}}</a>
       @endforeach
    </div>
  </div>

  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
            @if(isset($workloads))
            @foreach($days as $day)
        <div class="tab-pane fade show {{ $day['key'] == 'segunda' ? 'active' : '' }}" id="{{$day['key']}}" role="tabpanel" aria-labelledby="list-{{$day['key']}}-list">
      	<table class="table table-bordered">
      		<thead>
      			<tr>
      				<th>selecionar</th>
              <th>Entrada/Saída</th>
      			</tr>
      		</thead>
      		<tbody>
      			@foreach($workloads as $workload)
      			@if($workload->day===$day['value'])
						<tr>
							<td>
                <input id="{{$workload->id}}" type="checkbox" name="day[]}}" value="{{$workload->id}}"
                  @foreach($employee->workloads as $value)
                  @if($workload->id === $value->id) checked 
                  @endif 
                  @endforeach>
              </td>
							<td>
								{{$workload->start_time. '-'. $workload->exit_time}}
							</td>
						</tr>
					 @endif
      		 @endforeach
      		</tbody>
      	</table>
         </div>
    @endforeach
    @endif
  </div>
</div> <!-- Fim da coluna -->
<hr>
</div> <!-- Fim da row -->

<div class="row justify-content-end">
  <input type="submit" value="Enviar" class="btn btn-primary" style="cursor: pointer;">
</div>
{{ Form::close() }}
</div> <!-- Fim do container -->
     @endif
@endsection