routes/web.php
<?php

Route::resource('employees', 'EmployeeController');
Route::resource('points', 'PointController');
Route::resource('workloads', 'WorkloadController');
Route::get('reports', 'ReportController@index')->name('reports.index');
Route::post('reports', 'ReportController@generateByEmployee');

Route::post('employees/{id}/workloads', 'EmployeeController@createWorkload')->name('employee.workloads');
Route::get('employees/{id}/workloads', 'EmployeeController@workload')->name('employee.workloads');



Route::get('employees/{id}/status', 'EmployeeController@alterStatus');

resources/views/templates/header.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">{{ $title or 'Controle' }}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav ">
      <li class="nav-item">
        <a class="nav-link" href="{{ route('employees.index') }}">Colaborador <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ route('points.create') }}">Ponto <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ route('reports.index') }}">Relatórios <span class="sr-only">(current)</span></a>
      </li>
         <li class="nav-item">
        <a class="nav-link" href="{{ route('workloads.index') }}">Horários Exp. <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

resources/views/templates/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
	<link rel="stylesheet" href="assets/css/font-awesome.min.css">
	<title>{{ $title or 'Controle' }}</title>
</head>
<body>
 
@include('templates.header')

 @yield('content')


@stack('scripts')
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>